# Generated by Django 5.1.4 on 2025-11-02 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDIText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del texto académico', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Breve descripción del contenido', verbose_name='Descripción')),
                ('content', models.TextField(help_text='Contenido completo extraído del PDF/TXT', verbose_name='Contenido')),
                ('file', models.FileField(blank=True, help_text='Archivo PDF o TXT original', null=True, upload_to='pdi_texts/%Y/%m/', verbose_name='Archivo')),
                ('topic', models.CharField(default='General', help_text='Ej: Filtros, Transformaciones, Segmentación', max_length=100, verbose_name='Tema Principal')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20, verbose_name='Dificultad')),
                ('estimated_time_minutes', models.IntegerField(default=30, help_text='Tiempo estimado de lectura', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)], verbose_name='Tiempo Estimado (minutos)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('order', models.IntegerField(default=0, help_text='Orden de presentación (menor número = primero)', verbose_name='Orden')),
                ('has_quiz', models.BooleanField(default=False, help_text='Se marca automáticamente cuando se genera el cuestionario', verbose_name='¿Tiene Cuestionario?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_texts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Texto PDI',
                'verbose_name_plural': 'Textos PDI',
                'db_table': 'pdi_text',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitialQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_json', models.JSONField(help_text='Array de objetos con estructura: {pregunta, opciones[], respuesta_correcta, tema, explicacion}', verbose_name='Preguntas (JSON)')),
                ('total_questions', models.IntegerField(default=20, verbose_name='Total de Preguntas')),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt enviado a Gemini Pro para generar este quiz', verbose_name='Prompt Usado')),
                ('generation_time_seconds', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Generación (segundos)')),
                ('model_used', models.CharField(default='gemini-2.5-pro', max_length=16000, verbose_name='Modelo de IA Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_quiz', to='pdi_texts.pditext', verbose_name='Texto PDI')),
            ],
            options={
                'verbose_name': 'Cuestionario Inicial',
                'verbose_name_plural': 'Cuestionarios Iniciales',
                'db_table': 'initial_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pditext',
            index=models.Index(fields=['status', 'order'], name='pdi_text_status_32881f_idx'),
        ),
        migrations.AddIndex(
            model_name='pditext',
            index=models.Index(fields=['topic'], name='pdi_text_topic_068dbb_idx'),
        ),
    ]
