# Generated by Django 5.1.4 on 2025-11-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pditext',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Contenido completo extraído del PDF/TXT', verbose_name='Contenido'),
        ),
    ]
