# Generated by Django 5.1.4 on 2025-11-02 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0002_alter_pditext_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_topics', models.JSONField(default=list, help_text='Historial de todos los temas donde ha fallado', verbose_name='Temas Débiles Acumulados')),
                ('study_streak', models.IntegerField(default=0, help_text='Días consecutivos estudiando', verbose_name='Racha de Estudio (días)')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Estudio')),
                ('material_preferences', models.JSONField(default=dict, help_text='Tipos de material que prefiere el usuario', verbose_name='Preferencias de Material')),
                ('total_study_time_minutes', models.IntegerField(default=0, verbose_name='Tiempo Total de Estudio (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(help_text='1, 2, 3...', verbose_name='Número de Intento')),
                ('score', models.FloatField(help_text='Porcentaje de respuestas correctas (0-100)', verbose_name='Puntuación')),
                ('answers_json', models.JSONField(help_text='Array de objetos: [{question_id, selected_answer, is_correct}]', verbose_name='Respuestas (JSON)')),
                ('weak_topics', models.JSONField(default=list, help_text="Lista de temas donde falló: ['Filtros Gaussianos', 'Canny']", verbose_name='Temas Débiles')),
                ('time_spent_seconds', models.IntegerField(help_text='Tiempo que tardó en completar el cuestionario', verbose_name='Tiempo Empleado (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del intento')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pdi_texts.initialquiz', verbose_name='Cuestionario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Intento de Cuestionario',
                'verbose_name_plural': 'Intentos de Cuestionarios',
                'db_table': 'quiz_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='quiz_attemp_user_id_465dd1_idx'), models.Index(fields=['quiz', 'user'], name='quiz_attemp_quiz_id_9e84ee_idx')],
            },
        ),
    ]
