# Generated by Django 5.1.4 on 2025-11-02 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0003_userprofile_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Árbol de Decisión'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo de Material')),
                ('quiz_before_score', models.FloatField(help_text='Puntuación antes de usar el material', verbose_name='Score Antes')),
                ('quiz_after_score', models.FloatField(help_text='Puntuación después de usar el material', verbose_name='Score Después')),
                ('improvement', models.FloatField(help_text='Diferencia: after - before', verbose_name='Mejora')),
                ('time_spent_minutes', models.IntegerField(help_text='Tiempo que pasó estudiando el material', verbose_name='Tiempo Estudiado (minutos)')),
                ('interactions_count', models.IntegerField(default=0, help_text='Número de clics, flips, expansiones', verbose_name='Interacciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_effectiveness', to='pdi_texts.pditext', verbose_name='Texto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_effectiveness', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Efectividad de Material',
                'verbose_name_plural': 'Efectividad de Materiales',
                'db_table': 'material_effectiveness',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'text', 'material_type'], name='material_ef_user_id_473b3c_idx'), models.Index(fields=['user', '-created_at'], name='material_ef_user_id_beb424_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Árbol de Decisión'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo de Material')),
                ('was_recommended', models.BooleanField(default=False, verbose_name='¿Fue Recomendado?')),
                ('followed_recommendation', models.BooleanField(blank=True, null=True, verbose_name='¿Siguió la Recomendación?')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='pdi_texts.quizattempt', verbose_name='Intento de Quiz')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='pdi_texts.pditext', verbose_name='Texto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
                'db_table': 'material_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'text'], name='material_re_user_id_e09044_idx'), models.Index(fields=['-requested_at'], name='material_re_request_ee8b75_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDidacticMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Árbol de Decisión'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo')),
                ('html_content', models.TextField(help_text='HTML sanitizado', verbose_name='HTML')),
                ('weak_topics', models.JSONField(verbose_name='Temas Enfocados')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generado')),
                ('generation_time_seconds', models.IntegerField(blank=True, null=True, verbose_name='Tiempo Generación')),
                ('was_effective', models.BooleanField(blank=True, null=True, verbose_name='¿Efectivo?')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='didactic_materials', to='pdi_texts.quizattempt', verbose_name='Intento')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='didactic_materials', to='pdi_texts.pditext', verbose_name='Texto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='didactic_materials', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Material Didáctico',
                'verbose_name_plural': 'Materiales Didácticos',
                'db_table': 'user_didactic_material',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'text'], name='user_didact_user_id_59c66a_idx'), models.Index(fields=['material_type'], name='user_didact_materia_cab8ac_idx'), models.Index(fields=['-requested_at'], name='user_didact_request_4299a7_idx')],
            },
        ),
    ]
