# Generated by Django 5.1.4 on 2025-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdi_texts", "0004_materialeffectiveness_materialrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialeffectiveness",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("flashcard", "Flashcards"),
                    ("decision_tree", "Mapa Conceptual"),
                    ("summary", "Resumen Estructurado"),
                ],
                max_length=20,
                verbose_name="Tipo de Material",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("flashcard", "Flashcards"),
                    ("decision_tree", "Mapa Conceptual"),
                    ("summary", "Resumen Estructurado"),
                ],
                max_length=20,
                verbose_name="Tipo de Material",
            ),
        ),
        migrations.AlterField(
            model_name="userdidacticmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("flashcard", "Flashcards"),
                    ("decision_tree", "Mapa Conceptual"),
                    ("summary", "Resumen Estructurado"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
