# Generated by Django 5.1.4 on 2025-11-17 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0005_alter_materialeffectiveness_material_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialeffectiveness',
            name='material_type',
            field=models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Mapa Conceptual'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='material_type',
            field=models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Mapa Conceptual'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='userdidacticmaterial',
            name='material_type',
            field=models.CharField(choices=[('flashcard', 'Flashcards'), ('decision_tree', 'Mapa Conceptual'), ('mind_map', 'Mapa Mental'), ('summary', 'Resumen Estructurado')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID de Sesión')),
                ('started_at', models.DateTimeField(verbose_name='Inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('total_time_seconds', models.IntegerField(default=0, verbose_name='Tiempo Total (segundos)')),
                ('active_time_seconds', models.IntegerField(default=0, help_text='Tiempo real de interacción (sin idle)', verbose_name='Tiempo Activo (segundos)')),
                ('idle_time_seconds', models.IntegerField(default=0, verbose_name='Tiempo Inactivo (segundos)')),
                ('total_interactions', models.IntegerField(default=0, verbose_name='Total de Interacciones')),
                ('scroll_events', models.IntegerField(default=0, verbose_name='Eventos de Scroll')),
                ('click_events', models.IntegerField(default=0, verbose_name='Eventos de Click')),
                ('hover_events', models.IntegerField(default=0, verbose_name='Eventos de Hover')),
                ('focus_changes', models.IntegerField(default=0, verbose_name='Cambios de Foco')),
                ('sections_visited', models.JSONField(default=list, verbose_name='Secciones Visitadas')),
                ('max_scroll_depth', models.FloatField(default=0, verbose_name='Profundidad Máxima de Scroll (%)')),
                ('revisits_count', models.IntegerField(default=0, verbose_name='Número de Revisitas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('completed', models.BooleanField(default=False, verbose_name='Completó el Material')),
                ('exit_type', models.CharField(blank=True, choices=[('normal', 'Salida Normal'), ('timeout', 'Timeout por Inactividad'), ('browser_close', 'Cerró Navegador'), ('navigation', 'Navegó a otra página')], max_length=20, null=True, verbose_name='Tipo de Salida')),
                ('device_type', models.CharField(max_length=20, null=True, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(max_length=50, null=True, verbose_name='Navegador')),
                ('screen_resolution', models.CharField(max_length=20, null=True, verbose_name='Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='pdi_texts.userdidacticmaterial', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Estudio',
                'verbose_name_plural': 'Sesiones de Estudio',
                'db_table': 'study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=255, verbose_name='ID de Sección')),
                ('section_type', models.CharField(choices=[('weak_section', 'Sección de Temas Débiles'), ('review_section', 'Sección de Repaso'), ('flashcard', 'Flashcard'), ('tree_node', 'Nodo del Árbol'), ('summary_block', 'Bloque de Resumen'), ('comparison_table', 'Tabla Comparativa'), ('code_block', 'Bloque de Código')], max_length=50, verbose_name='Tipo de Sección')),
                ('section_content_preview', models.TextField(max_length=500, verbose_name='Preview del Contenido')),
                ('first_view_at', models.DateTimeField(verbose_name='Primera Vista')),
                ('last_view_at', models.DateTimeField(verbose_name='Última Vista')),
                ('total_time_seconds', models.FloatField(default=0, verbose_name='Tiempo Total (segundos)')),
                ('view_count', models.IntegerField(default=0, verbose_name='Número de Vistas')),
                ('interaction_count', models.IntegerField(default=0, verbose_name='Interacciones en Sección')),
                ('scroll_depth_percent', models.FloatField(default=0, verbose_name='Profundidad de Scroll (%)')),
                ('fully_read', models.BooleanField(default=False, verbose_name='Leído Completamente')),
                ('interacted_with', models.BooleanField(default=False, verbose_name='Interactuó con la Sección')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_times', to='pdi_texts.studysession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Tracking de Tiempo por Sección',
                'verbose_name_plural': 'Tracking de Tiempo por Sección',
                'db_table': 'section_time_tracking',
                'ordering': ['-total_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('hover', 'Hover'), ('focus', 'Cambio de Foco'), ('flashcard_flip', 'Voltear Flashcard'), ('node_expand', 'Expandir Nodo'), ('node_collapse', 'Colapsar Nodo'), ('section_view', 'Ver Sección'), ('copy_text', 'Copiar Texto'), ('tab_visible', 'Tab Visible'), ('tab_hidden', 'Tab Oculta'), ('resume_study', 'Reanudar Estudio'), ('pause_study', 'Pausar Estudio')], max_length=30, verbose_name='Tipo de Evento')),
                ('element_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Elemento')),
                ('element_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Elemento')),
                ('element_text', models.TextField(blank=True, null=True, verbose_name='Texto del Elemento')),
                ('x_position', models.IntegerField(blank=True, null=True, verbose_name='Posición X')),
                ('y_position', models.IntegerField(blank=True, null=True, verbose_name='Posición Y')),
                ('scroll_position', models.IntegerField(blank=True, null=True, verbose_name='Posición de Scroll')),
                ('viewport_height', models.IntegerField(blank=True, null=True, verbose_name='Alto del Viewport')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('time_since_session_start', models.FloatField(verbose_name='Tiempo desde Inicio (segundos)')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata Adicional')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pdi_texts.studysession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Evento de Interacción',
                'verbose_name_plural': 'Eventos de Interacción',
                'db_table': 'interaction_event',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.JSONField(default=list, help_text='Array de {x, y, timestamp}', verbose_name='Clics')),
                ('mouse_movements', models.JSONField(default=list, help_text='Array de {x, y, timestamp}', verbose_name='Movimientos del Mouse')),
                ('scroll_points', models.JSONField(default=list, help_text='Array de {position, timestamp}', verbose_name='Puntos de Scroll')),
                ('hot_zones', models.JSONField(default=list, help_text='Áreas con más actividad: [{x, y, width, height, intensity}]', verbose_name='Zonas Calientes')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Capturado')),
                ('data_points_count', models.IntegerField(default=0, verbose_name='Número de Puntos de Datos')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='pdi_texts.studysession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Datos de Heatmap',
                'verbose_name_plural': 'Datos de Heatmap',
                'db_table': 'heatmap_data',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-started_at'], name='study_sessi_user_id_791aba_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['material', '-started_at'], name='study_sessi_materia_80f93f_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['session_id'], name='study_sessi_session_03f759_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['is_active'], name='study_sessi_is_acti_fecf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiontimetracking',
            index=models.Index(fields=['session', 'section_id'], name='section_tim_session_d68d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiontimetracking',
            index=models.Index(fields=['section_type'], name='section_tim_section_2b2706_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectiontimetracking',
            unique_together={('session', 'section_id')},
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['session', 'timestamp'], name='interaction_session_6f406d_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['event_type'], name='interaction_event_t_20441f_idx'),
        ),
    ]
