# Generated by Django 5.1.4 on 2025-11-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdi_texts", "0006_alter_materialeffectiveness_material_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdidacticmaterial",
            name="total_flashcards",
            field=models.IntegerField(
                default=20, help_text="Número total de flashcards en el set"
            ),
        ),
        migrations.AddField(
            model_name="userdidacticmaterial",
            name="total_nodes",
            field=models.IntegerField(
                default=15,
                help_text="Número total de nodos en árbol/mapa (excluyendo raíz)",
            ),
        ),
    ]
