# Generated by Django 5.1.4 on 2025-12-30 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0007_userdidacticmaterial_total_flashcards_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_topics_order', models.JSONField(help_text='Lista estricta de los 20 temas extraídos del Initial Quiz. NO CAMBIA.')),
                ('current_session', models.IntegerField(default=0, help_text='0=Pre-Test, 1=Sesión 1, etc.')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi_texts.pditext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta de Aprendizaje',
                'unique_together': {('user', 'text')},
            },
        ),
        migrations.CreateModel(
            name='AdaptiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Corresponde al ciclo (1, 2, 3...)')),
                ('questions_json', models.JSONField(help_text='JSON con EXACTAMENTE 20 preguntas alineadas a fixed_topics_order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdi_texts.userdidacticmaterial')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi_texts.pditext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_quizzes', to='pdi_texts.studentlearningpath')),
            ],
            options={
                'verbose_name': 'Quiz Adaptativo',
                'ordering': ['session_number'],
            },
        ),
    ]
