# Generated by Django 5.1.4 on 2025-12-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0008_studentlearningpath_adaptivequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialeffectiveness',
            name='quiz_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('adaptive', 'Adaptive'), ('post_test', 'Post Test')], default='initial', max_length=20),
        ),
    ]
