# Generated by Django 5.1.4 on 2025-12-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_texts', '0009_materialeffectiveness_quiz_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_attemp_user_id_465dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_attemp_quiz_id_9e84ee_idx',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='pdi_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_attempts', to='pdi_texts.pditext', verbose_name='Texto PDI'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('adaptive', 'Adaptive'), ('post_test', 'Post Test')], default='initial', max_length=20, verbose_name='Tipo de Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='1, 2, 3...', verbose_name='Número de Intento'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pdi_texts.initialquiz', verbose_name='Cuestionario Inicial'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Tiempo que tardó en completar el cuestionario', verbose_name='Tiempo Empleado (segundos)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='weak_topics',
            field=models.JSONField(default=list, help_text='Lista de temas donde falló', verbose_name='Temas Débiles'),
        ),
    ]
